### ISSUE TITLE
How much in advance should one prepare?

### ISSUE THREAD

**Issue by lnnrtwttkhn** [matteocarpi/Tiramisu#1]
Arguably, Tiramisu can (or maybe even should) be prepared a day in advance to let everything sit and soak for a while. Is this true or should it be prepared as freshly as possible (e.g., due to the eggs)? I think this could be clarified further in the README.md. Thanks!

**Comment by matteocarpi** [comment]
Hey @lnnrtwttkhn Thanks for pointing that out!

I would say that there is a compromise to be made between freshness and settleness of the Tiramisù.

If the eggs are very fresh I wouldn't worry about the Tiramisù being eaten 24h later or earlier. I would say that the best would be to prepare it in the morning for the evening or in the evening for the lunch of the following day.
